name: onix_flutter_core
description: "Core package"
version: 0.0.1
#homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.17.0"

dependencies:
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_jailbreak_detection: ^1.10.0
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  graphql: ^5.2.0-beta.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^2.0.0
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.1
  logger: ^2.4.0
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  retry: ^3.1.2
  shared_preferences: ^2.3.2
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
#flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
