name: onix_flutter_core
description: "Onix Flutter Core package"
version: 0.0.1
repository: https://github.com/OnixFlutterTeam/onix-flutter-core

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  internet_connection_checker: ^2.0.0
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.2+1
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  retry: ^3.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
